require("utils")

g.node_host_prog = fn.trim(fn.system("asdf where nodejs 14.15.0")) .. "/.npm/lib/node_modules/neovim/bin/cli.js"
g.python_host_prog = fn.trim(fn.system("asdf where python 2.7.18")) .. "/bin/python"
g.python3_host_prog = fn.trim(fn.system("asdf where python 3.8.5")) .. "/bin/python"
g.ruby_host_prog = fn.trim(fn.system("asdf where ruby 2.7.1")) .. "/bin/ruby"

opt("b", "expandtab", true)
opt("b", "shiftwidth", 2)
opt("b", "swapfile", false)
opt("b", "tabstop", 2)
opt("b", "tabstop", 2)
opt("b", "tabstop", 2)
opt("o", "backup", false)
opt("o", "clipboard", "unnamed")
opt("o", "cmdheight", 2)
opt("o", "completeopt", "menu,menuone,noselect")
opt("o", "diffopt", "internal,filler,closeoff,vertical")
opt("o", "fillchars", "vert: ,stl: ,stlnc: ,")
opt("o", "hidden", true)
opt("o", "hlsearch", false)
opt("o", "ignorecase", true)
opt("o", "inccommand", "nosplit")
opt("o", "joinspaces", false)
opt("o", "langmenu", "en_US.UTF-8")
opt("o", "listchars", "tab:» ,trail:·,precedes:←,extends:→")
opt("o", "shortmess", "filnxtToOFc")
opt("o", "showbreak", "↪")
opt("o", "smartcase", true)
opt("o", "smartcase", true)
opt("o", "startofline", false)
opt("o", "termguicolors", true)
opt("o", "timeoutlen", 250)
opt("o", "updatetime", 100)
opt("o", "wrapscan", true)
opt("o", "writebackup", false)
opt("w", "cursorline", true)
opt("w", "foldenable", false)
opt("w", "foldmethod", "syntax")
opt("w", "list", true)
opt("w", "number", true)
opt("w", "relativenumber", true)
opt("w", "signcolumn", "yes")
